# Generated by Django 3.2.8 on 2021-12-14 02:30

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Genre Name')),
                ('genre_description', models.CharField(max_length=250, verbose_name='Genre Description')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Movie Name')),
                ('release_date', models.DateField(default=datetime.datetime.today, verbose_name='Release Date')),
                ('runtime', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='Runtime in Minutes')),
                ('dbmb_rating', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='DBMB Rating')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MoviePages.genre', verbose_name='Genre')),
            ],
        ),
    ]
