# Generated by Django 3.2.8 on 2021-12-14 02:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoviePages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='dbmb_rating',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='DBMB Rating'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='runtime',
            field=models.IntegerField(default=0, verbose_name='Runtime in Minutes'),
        ),
    ]
